id: PA52DE133
initial_creation_type: input
source_metadata:
  title: Chokling Tersar Series
  language: it
  description: 'Texts related to the Chokling Tersar (mchog gling gter gsar), the
    New Treasures of Chokgyur Lingpa (1829–1870):'
  volume:
    07da17b9b68c46d1b86db8a3d1b5ba0d:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    a8b7d7f45d0b4bdb90584f48bc18b4d3:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    120c62ee4bd14244a32f6c37057bad77:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    0d0a3ab87eab43cca1a12fc653896e61:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    17fc30b7ff484118b7a904c61561bd78:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    87291e5cf8b24b679d9d567341ec6dcb:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    da22cfed41ae4c2bbf6088544e33c43f:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Commentaries
    e1c624afc9a94dc7a8b86e4e680afbe4:
      title: 'The Vajra Words Unveiled: A Commentary on the Düsum Sangyé Prayer to
        the Guru'
      parent: Commentaries
    c1e0e9e9fe5a4062bc8dcdcc81ca303c:
      title: The Lament of Rudra
      parent: Confession
    17ceea3b70f74d938feb15c9685aaaae:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Lineage Prayers
    6ca0aa77e8c94f72aab1dbd2bdfc4917:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Prayers
    810316a25a054203b9ea5de074bf75d1:
      title: The Prayer in Six Vajra Lines
      parent: Prayers
    4e7fff5d88124c1da8eca9e09d407676:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Prayers
    2a10a4ca0f064affaeb67747bee81daf:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Prayers
    5c1d9a25920c4b8d8e5e8e56ad05428f:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    bd9bf2a14ea54bca984f0d3cee9b33ff:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    fbfaddd763864535bbb981e753a8a893:
      title: Extremely Secret Unelaborate Daily Sādhana for the Heart Practice of
        the Great Demon-Slayer
      parent: Sādhanas
    270dc3a315dc47f4878a21779cc01000:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Sur Offering
    50ca22fbf7e44166b012a723b5699621:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-03-01T03:13:53.994669'
last_modified_at: '2022-03-01T03:13:53.994671'
